# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b56a3c5fc32953e9e273f584a9dc5ef25862436f2b790dbe06a81dfe9d3a8c40246f27874eedf90222a0bc59116d32b9ec5f56c8c5e2d085dd866500ddd60e23

test:
  secret_key_base: 08edb2611f9cbc5c9808e7291381bc9cabb293430a382b056e89377c632a7e61f069d396bc8ef1728d219c98e07a1a12c87272d1144b8b5e11e36c4bc13bd264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
